### ISSUE TITLE
Use JFreeSVG instead of Apache Batik

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/jfreechart#2]
Replacing the batik libraries with JFreeSVG will save a lot of space (44k in stead of 3-4 Meg) and will prevent potential JAR collisions.

License must be checked (AGPL) which is probably incompatible with L-GPL 2.1

http://www.jfree.org/phpBB2/viewforum.php?f=32
http://www.jfree.org/jfreesvg/
http://dolf.trieschnigg.nl/jfreechart/

**Comment by dizzzz** [comment]
The author of jfreesvg suggest that only a part of the batik/svg dependancy tree is required; just some cherry picking of some classes would be sufficient.

**Comment by ljo** [comment]
Yes, I try to do that for some other packages too. But I cannot say I have the full extent of classes  covered yet. There are also some very good reasons to stay with using the providers packaging either via ivy or maven like now.

**Comment by dizzzz** [comment]
made a step with https://github.com/eXist-db/jfreechart/pull/16
