### ISSUE TITLE
Update showcase UI to show all available chart

### ISSUE THREAD

**Issue by dizzzz** [eXist-db/jfreechart#7]
The showcase is right now a simple collection of a few charts.
Without too much effort we could make a simple UI with a drop down-selection box containing the ChartNames, and an example chart just below that.

Ideally a xquery function would be available to get the list of supported charts, with some meta information e.g. to describe what type of XML data is required for that chart.

Drawback.... redundancy and additional maintenance.

**Comment by ljo** [comment]
I agree, but we should make it as low overhead as possible and not introduce any further dependencies.
